### ISSUE TITLE
API key should not be on git repository

### ISSUE THREAD

**Issue by engmedhat51** [AhmadElMelegy/Popular-Movies-App#1]
I think you should remove your API key

Storing API Keys, or any other sensitive information, on a git repository is something to be avoided at all costs. Even if the repository is private, you should not see it as a safe place to store sensitive information.

https://medium.freecodecamp.org/how-to-securely-store-api-keys-4ff3ea19ebda

**Comment by mlegy** [comment]
Of course you are right.
this repo was created 3 years ago, and I don't maintain it now. If you like you can make a PR and I will merge it.
